/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'background': '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-bright': '#f8f9ff',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'primary-container': '#0b2545',
        'inverse-surface': '#213145',
        'outline-variant': '#c4c6cf',
        'tertiary': '#001404',
        'surface-tint': '#495f82',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#b1c7f0',
        'tertiary-fixed-dim': '#79db8d',
        'on-surface-variant': '#44474e',
        'outline': '#74777f',
        'on-primary-fixed': '#001c3b',
        'surface': '#f8f9ff',
        'on-surface': '#0b1c30',
        'primary': '#001026',
        'on-secondary-fixed-variant': '#004b73',
        'tertiary-container': '#002c0f',
        'secondary-fixed-dim': '#93ccff',
        'on-secondary-container': '#00476e',
        'secondary': '#006398',
        'surface-container-high': '#dce9ff',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed-variant': '#314769',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-primary-container': '#778db2',
        'secondary-fixed': '#cce5ff',
        'on-tertiary-container': '#3c9e57',
        'on-tertiary-fixed-variant': '#005323',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#95f8a7',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#b1c7f0',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#5bb8fe',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed': '#00210a',
        'on-secondary-fixed': '#001d31',
        'primary-fixed': '#d5e3ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '1rem',
        'gutter-compact': '0.5rem',
        'margin': '1.5rem',
      },
      fontFamily: {
        'sans': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'mono': ['JetBrains Mono', 'SFMono-Regular', 'Consolas', 'monospace'],
        'display': ['Space Grotesk', 'Inter', 'sans-serif'],
        'body-lg': ['Inter'],
        'headline-lg': ['Space Grotesk'],
        'display-md': ['Space Grotesk'],
        'body-sm': ['Inter'],
        'label-mono-md': ['JetBrains Mono'],
        'headline-sm': ['Space Grotesk'],
        'body-md': ['Inter'],
        'label-mono-lg': ['JetBrains Mono'],
        'label-mono-sm': ['JetBrains Mono'],
        'display-lg': ['Space Grotesk'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-mono-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-mono-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'surface': '0 1px 4px rgba(11,28,48,0.03)',
        'header': '0 1px 3px rgba(11,28,48,0.02)',
        'card': '0 1px 3px rgba(11,28,48,0.04)',
        'card-hover': '0 4px 12px rgba(11,28,48,0.08)',
      },
    },
  },
  plugins: [],
};
