/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // ============================================================
        // NAWI TRUST — DigiLocker-inspired design tokens
        // Indigo/violet primary, lavender surfaces, soft status colors.
        // Every view in the app already consumes these semantic names,
        // so this palette remap re-skins the whole product consistently.
        // ============================================================
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'background': '#ffffff',
        'surface-container-highest': '#DCD6FF',
        'surface-bright': '#ffffff',
        'on-primary': '#ffffff',
        'on-error-container': '#991B1B',
        'primary-container': '#4A3AFF',
        'inverse-surface': '#1A1A2E',
        'outline-variant': '#E7E4F7',
        'tertiary': '#052e16',
        'surface-tint': '#4A3AFF',
        'inverse-on-surface': '#F6F5FF',
        'inverse-primary': '#C7B8FF',
        'tertiary-fixed-dim': '#4ADE80',
        'on-surface-variant': '#5A5A72',
        'outline': '#8B8AA3',
        'on-primary-fixed': '#2A1FB0',
        'surface': '#F6F5FF',
        'on-surface': '#1A1A2E',
        'primary': '#4A3AFF',
        'on-secondary-fixed-variant': '#4338CA',
        'tertiary-container': '#052e16',
        'secondary-fixed-dim': '#C7B8FF',
        'on-secondary-container': '#4338CA',
        'secondary': '#7C3AED',
        'surface-container-high': '#E6E1FF',
        'surface-container-low': '#F4F2FF',
        'on-primary-fixed-variant': '#2A1FB0',
        'error': '#DC2626',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#E7E4F7',
        'on-primary-container': '#ffffff',
        'secondary-fixed': '#EEEBFF',
        'on-tertiary-container': '#16A34A',
        'on-tertiary-fixed-variant': '#065F46',
        'error-container': '#FEE2E2',
        'tertiary-fixed': '#DCFCE7',
        'on-background': '#1A1A2E',
        'primary-fixed-dim': '#C7B8FF',
        'surface-variant': '#EEEBFF',
        'secondary-container': '#7C3AED',
        'surface-container': '#EEEBFF',
        'on-tertiary-fixed': '#065F46',
        'on-secondary-fixed': '#4A3AFF',
        'primary-fixed': '#EEEBFF',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.625rem',
        xl: '0.875rem',
        '2xl': '1.125rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'gutter': '1rem',
        'gutter-compact': '0.5rem',
        'margin': '1.5rem',
      },
      fontFamily: {
        'sans': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'mono': ['JetBrains Mono', 'SFMono-Regular', 'Consolas', 'monospace'],
        'display': ['Inter', 'sans-serif'],
        'body-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'display-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-mono-md': ['JetBrains Mono'],
        'headline-sm': ['Inter'],
        'body-md': ['Inter'],
        'label-mono-lg': ['JetBrains Mono'],
        'label-mono-sm': ['JetBrains Mono'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'body-lg': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'headline-lg': ['20px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'label-mono-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-mono-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      boxShadow: {
        'surface': '0 2px 8px rgba(74,58,255,0.05)',
        'header': '0 1px 3px rgba(74,58,255,0.04)',
        'card': '0 2px 10px rgba(74,58,255,0.07)',
        'card-hover': '0 10px 28px rgba(74,58,255,0.16)',
        'hero': '0 16px 40px rgba(74,58,255,0.28)',
      },
    },
  },
  plugins: [],
};
